<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Draw Line</title>
<style type="text/css">
      body { margin: 20px; font-family: arial,verdana,helvetica; background: #fff;}
      h1 { font-size: 140%; font-weight:normal; color: #036; border-bottom: 1px solid #ccc; }
      canvas { border: 2px solid #000; cursor: crosshair; float: left; margin-right: 20px; margin-bottom: 20px; }
      pre { float:left; display:block; background: rgb(238,238,238); border: 1px dashed #666; padding: 15px 20px; margin: 0 0 10px 0; }
      tr.green td { background-color: green; } 
	  tr.red td { background-color: red; }
      #box3 { width: 1cm; } 
    </style>
	<script type='text/javascript' src='http://code.jquery.com/jquery-1.8.3.min.js'></script>
</head>
<body>
	<?php echo $this->layout()->content ?>	
</body>
</html>
